# This configuration file is used for setting up keypoint detection model training following the Ultralytics pose dataset format.

# In our scenario have a data set of images from an autoinjector. The data set have two classes: 
#   1. capped (the autoinjector is capped)
#   2. uncapped (the autoinjector is uncapped)
# And each has two keypoints:
#   1. the front or the tip of the autoinjector, where the needle is located.
#   2. the base or the back of the autoinjector.

# For more information, see the Ultralytics documentation: https://docs.ultralytics.com/datasets/pose/#dataset-yaml-format

path: ./data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [2, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1]

# Classes
names:
  0: capped
  1: uncapped